# This is a sample build configuration for Java (Maven).
# Check our guides at https://confluence.atlassian.com/x/zd-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: maven:3.3.9

pipelines:
  default:
  - step:
      name: Dummy Start Step
      script:
      - echo "We out here testing!"
  - step:
      name: Execute Tests FireFox -Prod
      trigger: manual
      services:
      - docker
      script: # Modify the commands below to build your repository.
      - docker run -d --name ff_browser -p 5900:5900 -p 4444:4444 -e JAVA_OPTS=-Xmx512m selenium/standalone-firefox
      - mvn clean install -B -Denv=prod -Dbrowser=firefox -DbrowserLocation=remote -Dcucumber.options="--tags @activeMonitorApi,@activeMonitor"
  - step:
      name: Execute Tests Chrome -Prod
      trigger: manual
      services:
      - docker
      script: # Modify the commands below to build your repository.
      - docker run -d --name chrome_browser -p 5900:5900 -p 4444:4444 -e JAVA_OPTS=-Xmx512m selenium/standalone-chrome
      - mvn clean install -B -Denv=prod -Dbrowser=firefox -DbrowserLocation=remote -Dcucumber.options="--tags @activeMonitorApi,@activeMonitor"
