# This is a sample build configuration for Java (Maven).
# Check our guides at https://confluence.atlassian.com/x/zd-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: maven:3.3.9

pipelines:
  default:
    - step:
        name: Execute Tests
        services:
          - docker
        script: # Modify the commands below to build your repository.
          - docker network create grid
          - docker run -d -p 4444:4444 --net grid --name selenium-hub selenium/hub:3.14.0-europium
#          - docker run -d --net grid -e HUB_HOST=selenium-hub -v /dev/shm:/dev/shm selenium/node-chrome:3.14.0-europium
          - docker run -d --net grid -e HUB_HOST=selenium-hub -v /dev/shm:/dev/shm selenium/node-firefox:3.14.0-europium
          - mvn clean install -Dbrowser=firefox -Denv=remote -Dheadless=true # -B batch mode makes Maven less verbose
