references:

  container_config: &container_config
    docker:
    # specify the version you desire here
    - image: circleci/openjdk:8-jdk-browsers
    working_directory: chmod -R 777  ~/medmen-bdd-automation

version: 2
jobs:
  build:
    <<: *container_config
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
    - checkout
    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "pom.xml" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run: mvn dependency:go-offline

    - save_cache:
        paths:
        - ~/.m2
        key: v1-dependencies-{{ checksum "pom.xml" }}

  # run tests!
  api-tests:
    <<: *container_config
    steps:
    - checkout
    - run:
        name: Execute API tests
        command: mvn install test -B -Dcucumber.options="--tags @activeMonitorApi"

  chrome-ui-tests:
    <<: *container_config
    steps:
    - checkout
    - run:
        name: Execute Chrome UI test
        command: mvn install test -B -Denv=prod -Dbrowser=chrome -Dcucumber.options="--tags @activeMonitor"

  firefox-ui-tests:
    <<: *container_config
    steps:
    - checkout
    - run:
        name: Execute Firefox UI test
        command: mvn install test -B -Denv=prod -Dbrowser=firefox -Dcucumber.options="--tags @activeMonitor"

#cron job for every 2 hours
#workflows:
#  version: 2
#  active_monitor:
#    triggers:
#    - schedule:
#        cron: "0 0,2,4,6,8,10,12,14,16,18,20,22 * * *"
#        filters:
#          branches:
#            only:
#            - master
#    jobs:
#    - api-tests
#    - chrome-ui-tests
#    - firefox-ui-tests